# *******************************************************************************************
# *******************************************************************************************
#
#		Name : 		Makefile
#		Purpose :	Build module
#		Date :		20th March 2025
#		Author : 	Paul Robson (paul@robsons.org.uk)
#
# *******************************************************************************************
# *******************************************************************************************

include ../build_env/common.make

#
#		This just test it builds, nothing else.
#
test:
	$(ASSEMBLER) $(ASMOPTIONS) fwrapper.asm $(ASMTARGETS)
	echo "Assembles correctly"